version: "3.9"

services:
  nginx:
    build:
      dockerfile: ./requirements/NGINX/Dockerfile
    image: nginx
    container_name: nginx
    env_file:
      - ./.env
    ports:
      - "443:443"
    networks:
      - my_custom
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build:
      dockerfile: ./requirements/WordPress/Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - my_custom
    depends_on:
      - mariadb
    expose:
      - "9000:9000"
    restart: always

  mariadb:
    build:
      dockerfile: ./requirements/MariaDB/Dockerfile
    image: mariadb
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my_custom
    expose:
      - "3306:3306"
    restart: always

networks:
  my_custom:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/${USER}/data/wordpress'
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/${USER}/data/mariadb'